/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tickets/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Ticket */
        post: operations["analyze_ticket_api_v1_tickets_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Feedback */
        post: operations["record_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Tickets */
        get: operations["demo_tickets_api_v1_demo_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfidenceFactors */
        ConfidenceFactors: {
            /** Evidence Strength */
            evidence_strength: number;
            /** Relevance */
            relevance: number;
            /** Source Diversity */
            source_diversity: number;
            /** Retrieval Agreement */
            retrieval_agreement: number;
            /** Citation Coverage */
            citation_coverage: number;
            /**
             * Label
             * @enum {string}
             */
            label: "strong" | "sufficient" | "weak";
            /** Threshold */
            threshold: number;
        };
        /** DemoTicket */
        DemoTicket: {
            /** Id */
            id: string;
            /** Subject */
            subject: string;
            /** Description */
            description: string;
            /** Product Area */
            product_area: string;
            /**
             * Expected Action
             * @enum {string}
             */
            expected_action: "draft" | "escalate";
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Chunk Id */
            chunk_id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Heading */
            heading: string;
            /** Url */
            url: string;
            /** Excerpt */
            excerpt: string;
            /** Relevance */
            relevance: number;
            /** Dense Score */
            dense_score: number | null;
            /** Sparse Score */
            sparse_score: number | null;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Analysis Id */
            analysis_id: string;
            /**
             * Helpfulness
             * @enum {string}
             */
            helpfulness: "helpful" | "not_helpful";
            /** Accepted */
            accepted: boolean;
            /** Correction */
            correction?: string | null;
            /** Comment */
            comment?: string | null;
            /** Minutes Saved */
            minutes_saved?: number | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /**
             * Status
             * @constant
             */
            status: "recorded";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ResolutionStep */
        ResolutionStep: {
            /** Title */
            title: string;
            /** Instruction */
            instruction: string;
            /** Citations */
            citations: string[];
        };
        /** TicketAnalysisResponse */
        TicketAnalysisResponse: {
            /** Analysis Id */
            analysis_id: string;
            /** Category */
            category: string;
            /** Summary */
            summary: string;
            /** Steps */
            steps: components["schemas"]["ResolutionStep"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            confidence: components["schemas"]["ConfidenceFactors"];
            /**
             * Action
             * @enum {string}
             */
            action: "draft" | "escalate";
            /** Escalation Rationale */
            escalation_rationale: string[];
            /** Missing Signals */
            missing_signals: string[];
            /** Corpus Version */
            corpus_version: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "gemini" | "ollama" | "mock";
            /** Provider Model */
            provider_model: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** TicketAnalyzeRequest */
        TicketAnalyzeRequest: {
            /** Subject */
            subject: string;
            /** Description */
            description: string;
            /** Product Area */
            product_area?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_ticket_api_v1_tickets_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_tickets_api_v1_demo_tickets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoTicket"][];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
